name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.1"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
